#!/usr/bin/env bash

set -euo pipefail

# Constants
__name='rltt'
__scraper_directory='/media/storage/Projects/coding/RocketLeagueTradingTools/src/RocketLeagueTradingTools.Scraper/bin/Debug/net6.0/publish'
__web_directory='/media/storage/Projects/coding/RocketLeagueTradingTools/src/RocketLeagueTradingTools.Web/bin/Debug/net6.0/publish'

function show_usage() {
    cat <<EOF
Usage:
    $__name <COMMAND> [ -h | --help ]

Commands:
    scrap
        Starts scraping CLI.

    web
        Starts UI web application.

Options:
    -h, --help
        Print synopsis.
EOF
}

function start_scraper() {
    (cd "$__scraper_directory"; dotnet RocketLeagueTradingTools.Scraper.dll)
}

function start_web() {
    (cd "$__web_directory"; dotnet RocketLeagueTradingTools.Web.dll --urls http://localhost:7070/)
}

function open_settings() {
    case $commandName in
        scrap)
            (cd "$__scraper_directory"; editor appsettings.json)
            exit 0
            ;;
        web)
            (cd "$__web_directory"; editor appsettings.json)
            exit 0
            ;;
        *)
            echo >&2 "Settings are not available for '$commandName' command."
            exit 1
            ;;
    esac

}

function parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h | --help)
                show_usage
                exit 0
                ;;
            -s | --settings)
                settingsOption='true'
                shift
                ;;
            -* | --*)
                echo >&2 "Unknown option $1."
                exit 1
                ;;
            scrap | web)
                commandName="$1"
                shift
                ;;
            *)
                shift
                ;;
        esac
    done
}

function main() {
    # Default argument values
    local commandName=''
    local settingsOption='false'

    parse_args "$@"

    # No command arguments given
    if [ -z "$commandName" ] ; then
        show_usage
        exit 0
    fi

    if [ "$settingsOption" = 'true' ] ; then 
        open_settings
        exit 0
    fi

    if [ "$commandName" = 'scrap' ] ; then 
        start_scraper
        exit 0
    fi

    if [ "$commandName" = 'web' ] ; then 
        start_web
        exit 0
    fi
}

main "$@"
